type Project = {
  title: string;
  description: string;
  longDescription: string;
  technologies: string[];
  features: string[];
  liveUrl?: string;
  githubUrl: string;
  category: string;
  img?: string;
  year: number;
};

const projects = [
  {
    title: "DevZoku",
    description:
      "Empowering Collaboration in the World of Hackathons. A modern hackathon management platform for developers, organizers, and the wider hackathon community.",
    longDescription:
      "DevZoku is a modern hackathon management platform built for developers, organizers, and the wider hackathon community. Discover and join hackathons, form teams, manage events, and receive intelligent recommendations. Features include profile management, team collaboration, project management, hackathon discovery, notifications, organizer tools and AI-driven matching. Built with Next.js, Express, PostgreSQL, Qdrant, and more.",
    technologies: [
      "Next.js",
      "Express.js",
      "Cloudinary",
      "MistralAI",
      "Google Gemini",
      "Socket.io",
      "LangChain.js",
      "CRON Jobs",
      "TypeScript",
      "PostgreSQL",
      "Drizzle ORM",
      "Bun",
      "Valkey",
      "BullMQ",
      "Docker",
      "GitHub Actions",
      "Qdrant",
      "Tailwind CSS",
      "React Hook Form",
      "Framer Motion",
    ],
    features: [
      "Developer & Organizer profile management",
      "Team creation and collaboration tools",
      "Project portfolio and management",
      "Hackathon discovery and recommendations",
      "Real-time notifications",
      "AI-powered event and team matching",
      "Hackathon creation and management for organizers",
      "Automated email notifications",
      "Secure authentication and file storage",
      "Responsive, accessible UI",
    ],
    liveUrl: "https://devzoku.app",
    githubUrl: "https://github.com/celersneha/devzoku",
    category: "Web Application",
    img: "/projects/Devzoku.png",
    year: 2025,
  },
  {
    title: "InvisiFeed",
    description:
      "A revolutionary anonymous feedback platform that enables honest communication in educational and professional environments.",
    longDescription:
      "InvisiFeed transforms feedback culture by providing a secure, anonymous platform for students and employees to share honest opinions. Built with Next.js and features AI-powered sentiment analysis.",
    technologies: [
      "Next.js",
      "JavaScript",
      "MongoDB",
      "Tailwind CSS",
      "Bcrypt",
      "Nodemailer",
      "Mongoose",
      "NextAuth.js",
      "Cloudinary",
      "pdf-lib",
      "Recharts",
      "Gemini 2.0 Flash API",
      "Razorpay",
      "CRON Jobs",
      "Shadcn",
      "Framer Motion",
      "React Hook Form",
      "Zod",
    ],
    features: [
      "Smart Invoice System with embedded feedback forms and reward coupons",
      "Anonymous feedback collection for honest client responses",
      "AI-powered feedback analysis (Gemini 2.0 Flash API)",
      "Integrated coupon rewards revealed after feedback submission",
      "Business analytics dashboard with sales, feedback, and service metrics",
      "Automated invoice and coupon management with CRON jobs",
      "Flexible subscription plans with trial and auto-downgrade",
      "Sample testing mode for demo experience",
      "Secure account and data management",
      "Real-time notifications",
      "Admin dashboard",
    ],
    liveUrl: "https://invisifeed.vercel.app",
    githubUrl: "https://github.com/celersneha/invisifeed",
    category: "Web Application",
    img: "/projects/Invisifeed.png",
    year: 2025,
  },
  {
    title: "InactiTab",
    description:
      "Chrome extension that automatically detects and manages inactive browser tabs to improve performance and reduce memory usage.",
    longDescription:
      "InactiTab is a smart browser extension that monitors tab activity and automatically suspends inactive tabs, resulting in 30% better browser performance and reduced memory consumption.",
    technologies: [
      "JavaScript",
      "Browser APIs",
      "Manifest V3",
      "Vite",
      "TailwindCSS",
    ],
    features: [
      "Automatic tab tracking and inactivity detection with sleep indicators (💤)",
      "Smart protection for tabs with media playback, video calls, pinned tabs, and whitelisted domains",
      "Real-time CPU and memory usage monitoring for each tab with color-coded indicators",
      "Bulk tab management: multi-select, sort, filter, and batch close/whitelist tabs",
      "Customizable inactivity timers and behavior settings",
      "Auto-close history with restoration and configurable retention limits",
      "Manual and automatic tab protection options",
      "Visual feedback for tab states and resource usage",
      "Manifest V3 Chrome extension architecture for security and performance",
    ],
    liveUrl: "https://inactitab.vercel.app",
    githubUrl: "https://github.com/celersneha/inactitab",
    category: "Browser Extension",
    img: "/projects/Inactitab.png",
    year: 2025,
  },
  {
    title: "EduZen",
    description:
      "AI-powered learning companion that personalizes education for students.",
    longDescription:
      "EduZen is a comprehensive AI education platform that transforms how students interact with academic content. It features AI syllabus analysis, intelligent test generation, smart answer explanations, AI-powered analytics, and adaptive learning. Built with Next.js 15, MongoDB, Google Gemini 2.0 Flash, and more.",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Shadcn",
      "Framer Motion",
      "React Hook Form",
      "Zod",
      "MongoDB",
      "Mongoose",
      "NextAuth.js",
      "Gemini 2.0 Flash API",
      "PDF Processing",
    ],
    features: [
      "AI-powered syllabus analyzer & organizer",
      "Intelligent test generator with difficulty scaling",
      "Smart answer explanations",
      "AI performance analytics & insights",
      "Adaptive learning experience",
      "Secure authentication with NextAuth",
      "Subject management with PDF upload",
      "Comprehensive performance dashboard",
      "Personalized study recommendations",
    ],
    liveUrl: "",
    githubUrl: "https://github.com/celersneha/EduZen",
    category: "Web Application",
    img: "/projects/EduZen.png",
    year: 2025,
  },
  {
    title: "PdfIQ",
    description:
      "Full-stack app to upload PDFs and chat with them using AI. Built with Next.js 15, Bun, Mistral AI, Gemini AI, and Qdrant vector search.",
    longDescription:
      "PdfIQ is a sophisticated full-stack application that enables users to upload PDF documents and engage in intelligent conversations using AI. Features include PDF upload and parsing, AI-powered chat with Mistral AI, Gemini AI, conversation memory, multi-file context selection, semantic vector search with Qdrant, and secure authentication with Clerk. Built with Next.js, Bun runtime, Express.js, PostgreSQL, and more.",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Shadcn",
      "TanStack React Query v5",
      "Axios",
      "Lucide React",
      "Streamdown",
      "Bun",
      "Express.js",
      "Drizzle ORM",
      "PostgreSQL",
      "Qdrant",
      "Valkey",
      "Adminer",
      "Docker",
      "Docker Compose",
      "pdf-parse",
      "Multer",
      "BullMQ",
      "LangChain.js",
      "LangGraph",
      "MistralAI",
      "Google Gemini",
      "Clerk",
    ],
    features: [
      "PDF upload & processing",
      "AI-powered chat with document context",
      "Conversation memory across sessions",
      "Multi-file context selection",
      "Document analysis & chunking",
      "Semantic vector search with Qdrant",
      "Real-time streaming AI responses",
      "User authentication with Clerk",
      "Background processing with BullMQ",
      "Modern, interactive UI",
    ],
    liveUrl: "",
    githubUrl: "https://github.com/celersneha/chat-with-pdf",
    category: "Web Application",
    img: "/projects/Documind.png",
    year: 2025,
  },
  {
    title: "TickTask",
    description:
      "A modern full-stack todo app with GraphQL, React, TypeScript, and MongoDB. Sleek UI, JWT auth, live updates, and elegant experience.",
    longDescription:
      "TickTask is a sleek, modern full-stack todo application powered by GraphQL, React, TypeScript, and MongoDB. It features secure authentication, real-time updates, smart filtering, notifications, and a beautiful blue-purple gradient theme. Built with Apollo Client/Server, Styled Components, React Hook Form, and JWT authentication for a seamless and secure experience.",
    technologies: [
      "React.js",
      "TypeScript",
      "Apollo Client",
      "Styled Components",
      "React Router",
      "React Hook Form",
      "Feather Icons",
      "Node.js",
      "Express.js",
      "Apollo Server",
      "MongoDB",
      "Mongoose",
    ],
    features: [
      "User authentication with JWT",
      "Create, view, update, delete todos",
      "Smart filtering by completion",
      "Fully responsive design",
      "Live updates with GraphQL",
      "Elegant, accessible UI",
      "Notifications for actions",
      "Secure password hashing",
      "Protected GraphQL resolvers",
      "Input validation and sanitization",
    ],
    liveUrl: "",
    githubUrl: "https://github.com/celersneha/Todo-GraphQL",
    category: "Web Application",
    img: "/projects/TickTask.png",
    year: 2025,
  },
  {
    title: "RoastRadar",
    description:
      "A modern, full-stack anonymous roasting platform built with Next.js. Send and receive savage (but fun) anonymous feedback with AI-powered roast suggestions.",
    longDescription:
      "RoastRadar is a modern, full-stack anonymous messaging platform where users can send and receive savage (but fun) anonymous feedback. Features include anonymous messaging, AI-powered roast suggestions (Google Gemini), real-time dashboard, email verification, secure authentication, and a beautiful purple glassmorphism UI. Built with Next.js, MongoDB, NextAuth.js, shadcn/ui, and more.",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Shadcn",
      "Lucide React",
      "React Hook Form",
      "Zod",
      "Framer Motion",
      "Node.js",
      "MongoDB",
      "Mongoose",
      "NextAuth.js",
      "Nodemailer",
      "Google Gemini",
      "Vercel",
    ],
    features: [
      "Anonymous messaging",
      "AI-powered roast suggestions",
      "Real-time dashboard",
      "Email verification",
      "Secure authentication with NextAuth.js",
      "100% anonymous feedback",
      "Glass morphism UI",
      "Responsive, mobile-optimized design",
      "Input validation with Zod",
      "Modern purple gradient theme",
    ],
    liveUrl: "",
    githubUrl: "https://github.com/celersneha/RoastRadar",
    category: "Web Application",
    img: "/projects/RoastRadar.png",
    year: 2025,
  },
  {
    title: "CineHue",
    description:
      "A modern, responsive movie discovery application with real-time search, detailed movie info, and a beautiful dark UI powered by the OMDB API.",
    longDescription:
      "CineHue is a movie discovery platform built with React, React Router, and Tailwind CSS. It features real-time search suggestions, keyboard navigation, detailed movie pages, star ratings, and a modern dark theme. Powered by the OMDB API, CineHue offers a seamless and visually engaging way to explore movies. The app includes responsive design, smooth animations, custom loading screens, and a focus on accessibility and user experience.",
    technologies: [
      "React.js",
      "React Router",
      "TypeScript",
      "Tailwind CSS",
      "Axios",
      "Vite",
      "OMDB API",
    ],
    features: [
      "Real-time movie search with live suggestions",
      "Responsive movie grid and detailed pages",
      "Star rating system based on IMDB scores",
      "Smooth hover and loading animations",
      "Mobile-first responsive design",
      "Environment-based API key management",
    ],
    liveUrl: "https://cinehue.vercel.app",
    githubUrl: "https://github.com/celersneha/cinehue",
    category: "Web Application",
    img: "/projects/Cinehue.png",
    year: 2024,
  },
];

export default projects;
