export const siteConfig = {
  name: "Sneha Sharma",
  title:
    "Sneha Sharma - MERN Stack Developer | Next.js Expert | Building Scalable Web Applications",
  description:
    "Experienced MERN Stack Developer specializing in Next.js, React.js, Node.js, Express.js, MongoDB, and PostgreSQL. Building scalable, high-performance web applications with modern technologies. Based in Indore, India. Expert in RESTful APIs, GraphQL, and full-stack development.",
  url: "https://snehasharma.me",
  ogImage: "https://snehasharma.me/og-image.png",
  keywords: [
    "MERN Stack Developer",
    "Next.js Developer",
    "React.js Developer",
    "Langchain Developer",
    "Node.js Developer",
    "Full Stack Developer",
    "JavaScript Expert",
    "MongoDB Developer",
    "PostgreSQL",
    "Express.js",
    "GraphQL Developer",
    "RESTful API",
    "Web Developer Indore",
    "Frontend Developer India",
    "Backend Developer",
    "Sneha Sharma Developer",
    "Computer Science Engineering",
    "Acropolis Institute",
    "Chrome Extension Developer",
    "AI Integration Developer",
    "Payment Gateway Integration",
    "InvisiFeed",
    "InactiTab",
    "QuickBites",
    "Tailwind CSS",
    "TypeScript",
    "React Mastery",
    "NPTEL Certified",
    "Software Engineer India",
    "Web Application Developer",
    "Scalable Applications",
    "High Performance Apps",
  ],
  author: {
    name: "Sneha Sharma",
    email: "snehav2109@gmail.com",
    twitter: "@snehasharma",
    linkedin: "https://linkedin.com/in/ss0807",
    github: "https://github.com/SnehaSharma245",
    phone: "+91 87705 79552",
    location: "Indore, Madhya Pradesh, India",
    education:
      "B.Tech Computer Science Engineering - Acropolis Institute of Technology and Research",
    skills: [
      "Next.js",
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "PostgreSQL",
      "JavaScript",
      "C++",
      "GraphQL",
      "RESTful APIs",
    ],
  },
  social: {
    twitter: "https://twitter.com/SnehaDevs",
    linkedin: "https://linkedin.com/in/ss0807",
    github: "https://github.com/SnehaSharma245",
    email: "snehav2109@gmail.com",
  },
  projects: [
    {
      name: "InvisiFeed",
      description: "Anonymous Feedback Platform with AI-driven insights",
      url: "https://invisifeed.vercel.app",
      technologies: ["Next.js", "NextAuth", "Gemini API", "Razorpay"],
    },
    {
      name: "InactiTab",
      description: "Advanced Tab Activity Manager Chrome Extension",
      url: "https://inactitab.vercel.app",
      technologies: ["React", "Chrome APIs"],
    },
    {
      name: "QuickBites",
      description: "Scalable Online Food Delivery Platform",
      url: "https://github.com/SnehaSharma245/Food-Delivery",
      technologies: ["MERN", "JWT", "Stripe"],
    },
  ],
};

export const defaultMetadata = {
  title: {
    default: siteConfig.title,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: siteConfig.keywords,
  authors: [{ name: siteConfig.author.name, url: siteConfig.url }],
  creator: siteConfig.author.name,
  publisher: siteConfig.author.name,
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL(siteConfig.url),
  alternates: {
    canonical: siteConfig.url,
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    title: siteConfig.title,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: [
      {
        url: siteConfig.ogImage,
        width: 1200,
        height: 630,
        alt: siteConfig.title,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.title,
    description: siteConfig.description,
    images: [siteConfig.ogImage],
    creator: siteConfig.author.twitter,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large" as const,
      "max-snippet": -1,
    },
  },
  verification: {
    google: "IANU7tJOZ8duM6yXQwKjzF7YQml50jSng7SVGHo3du0",
  },
};

export const structuredData = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: siteConfig.author.name,
  url: siteConfig.url,
  image: `${siteConfig.url}/og-image.png`,
  description: siteConfig.description,
  jobTitle: "Full Stack Web Developer",
  worksFor: {
    "@type": "Organization",
    name: "Freelance",
  },
  address: {
    "@type": "PostalAddress",
    addressLocality: "Indore",
    addressCountry: "India",
  },
  email: siteConfig.author.email,
  sameAs: [
    siteConfig.social.linkedin,
    siteConfig.social.github,
    siteConfig.social.twitter,
  ],
  alumniOf: {
    "@type": "EducationalOrganization",
    name: "Acropolis Institute of Technology and Research",
  },
  knowsAbout: [
    "Web Development",
    "Frontend Development",
    "Backend Development",
    "React",
    "Next.js",
    "JavaScript",
    "TypeScript",
    "Langchain",
  ],
};
